version: '3'

services:
  kafka:
    image: confluentinc/cp-kafka:5.3.2
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      #      KAFKA_CREATE_TOPICS: "judge_in:1:1,judge_result:1:1"
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_NUM_PARTITIONS: 3
      CONFLUENT_SUPPORT_METRICS_ENABLE: 0
      KAFKA_BROKER_ID: 0
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:{{zookeeper_port}}
    ports: [ "{{kafka_port}}:9092" ]
    links: [ zookeeper ]
    volumes:
      - {{kafka_data}}/kafka:/var/lib/kafka/data
  zookeeper:
    image: confluentinc/cp-zookeeper:5.3.2
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports: [ "{{zookeeper_port}}:2181" ]
    volumes:
      - {{kafka_data}}/zookeeper/data:/var/lib/zookeeper/data
      - {{kafka_data}}/zookeeper/log:/var/lib/zookeeper/log
