[package]
name = "sphinx-core"
version = "0.1.0"
authors = ["Myriad-Dreamin <camiyoru@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "sphinx_core"
path = "src/lib.rs"

[dependencies]
toml = "0.5.3"
