[package]
name = "Sphinx-Core"
version = "0.1.0"
authors = ["9646516 <zyq855@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dockworker = "0.0.15"
json = "0.12.0"
crossbeam = "0.7.2"
rdkafka = "0.21.0"
futures = "0.1.29"
rdkafka-sys = "1.0.0"
