[package]
name = "Sphinx-Core"
version = "0.1.0"
authors = ["9646516 <zyq855@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dockworker = "0.0.14"
json = "0.11.15"
crossbeam = "0.7.2"
protobuf = "2.8.0"
futures = "0.1.28"
futures-cpupool = "0.1.8"
tls-api = "0.2.0"
grpc = "0.6.1"

[build-dependencies]
protoc-rust-grpc = "0.6.1"