refresh_rate: 30 seconds

appenders:
  stdout:
    kind: console
  requests:
    kind: rolling_file
    path: "log/main.log"
    encoder:
      kind: json
    policy:
      kind: compound
      trigger:
        kind: size
        limit: 10 mb
      roller:
        kind: fixed_window
        pattern: '{0}/main.log.{{}}'
        base: 1
        count: 5

root:
  level: info
  appenders:
    - stdout
    - requests