[package]
name = "sphinx-core-kafka-extension"
version = "0.1.0"
authors = ["Myriad-Dreamin <camiyoru@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
